/** Curated Material Symbols names for Storybook gallery & consumers. */
export const MATERIAL_ICON_NAMES = [
  // Navigation & actions
  'home',
  'menu',
  'close',
  'arrow_back',
  'arrow_forward',
  'arrow_upward',
  'arrow_downward',
  'chevron_left',
  'chevron_right',
  'expand_more',
  'expand_less',
  'more_vert',
  'more_horiz',
  'open_in_new',
  'refresh',
  'search',
  'filter_list',
  'sort',
  'tune',
  // Content
  'add',
  'remove',
  'edit',
  'delete',
  'content_copy',
  'content_cut',
  'content_paste',
  'save',
  'download',
  'upload',
  'share',
  'link',
  'attach_file',
  'print',
  // Communication
  'mail',
  'chat',
  'forum',
  'notifications',
  'campaign',
  'call',
  'videocam',
  // People & account
  'person',
  'group',
  'person_add',
  'account_circle',
  'badge',
  'manage_accounts',
  'login',
  'logout',
  // Status & feedback
  'check',
  'check_circle',
  'cancel',
  'info',
  'help',
  'warning',
  'error',
  'priority_high',
  'visibility',
  'visibility_off',
  'lock',
  'lock_open',
  'verified',
  // Media
  'image',
  'photo_camera',
  'play_arrow',
  'pause',
  'stop',
  'volume_up',
  'volume_off',
  'favorite',
  'favorite_border',
  'star',
  'star_border',
  // Files & folders
  'folder',
  'folder_open',
  'description',
  'article',
  'inventory_2',
  'cloud',
  'cloud_upload',
  'cloud_download',
  // Time & calendar
  'schedule',
  'calendar_today',
  'event',
  'history',
  'timer',
  // Maps & places
  'place',
  'map',
  'my_location',
  'directions',
  'explore',
  // Commerce
  'shopping_cart',
  'shopping_bag',
  'payments',
  'credit_card',
  'store',
  'local_offer',
  // Settings & system
  'settings',
  'build',
  'dashboard',
  'analytics',
  'insights',
  'apps',
  'widgets',
  'extension',
  'code',
  'terminal',
  'bug_report',
  'security',
  'shield',
  'key',
  'language',
  'dark_mode',
  'light_mode',
  'palette',
  // Layout
  'grid_view',
  'view_list',
  'view_module',
  'fullscreen',
  'fullscreen_exit',
  'split_screen',
  'drag_indicator',
] as const;

export type MaterialIconName = (typeof MATERIAL_ICON_NAMES)[number];
